### ISSUE TITLE
Metadata issue with typst universe template and the GitHub repo link

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [flavio20002/typst-orange-template#20]
On the [typst universe page](https://typst.app/universe/package/orange-book/), the repository metadata points to https://github.com/typst/templates instead of https://github.com/flavio20002/typst-orange-template.

The following should be updated:
> Repository: [GitHub](https://github.com/typst/templates)

> This template is a project of Flavio Barisi. Report issues on [their repository](https://github.com/typst/templates).

> Please report this template to the Typst team using the [contact form](https://typst.app/contact) if you believe it is a safety hazard or >infringes upon your rights.

**Comment by flavio20002** [comment]
Hi, thanks. Opened a pull request: https://github.com/typst/packages/pull/912
