### ISSUE TITLE
Need help to set Appendices Section

### ISSUE THREAD

**Issue by PullGuy** [flavio20002/typst-orange-template#23]
If I want to set the Appendices section as follows:
![Clip_2024-10-19_21-46-32](https://github.com/user-attachments/assets/6881d637-dc76-44b5-b255-da23bfebeafc)
just like the picture uploaded, the circle 1 and circle 2 are no need, How can I exclude it?

**Comment by flavio20002** [comment]
At the moment is not possible, but i can add a parameter to allow that

**Comment by PullGuy** [comment]
Thanks very much!

**Comment by flavio20002** [comment]
Can you upload here the code to make point 2 appear? I can't see it in my tests. Thanks

**Comment by PullGuy** [comment]
> Can you upload here the code to make point 2 appear? I can't see it in my tests. Thanks
Because I don't want to display the list of figures and tables in the book, I commented out the lines `list-of-figure-title: "List of Figure"` and `list-of-table-title: "List of Table"` in the `#show book.with( )` section in the file `main.typ`.

**Comment by PullGuy** [comment]
By the way, a humble suggestion:

1. You might consider using the [numbly package](https://github.com/flaribbit/numbly) to customize titles of different levels, such as "Chapter 1", which could potentially enhance the reading experience;
2. Since the locate function will be deprecated in the new version of Typst, it might be a good idea to consider using the context function to achieve the corresponding functionality.

**Comment by flavio20002** [comment]
Fixed all in version"0.3.0":

- I added a new parameter to:

`#show: appendices.with("Appendices", hide-parent: false)`

to hide the name Appendices from the index.

- I migrated depecrated functions, so no warning is visible.
