### ISSUE TITLE
Some bug fix

### ISSUE THREAD

**Issue by typetypewriter** [flavio20002/typst-orange-template#25]
in lib.typ

1 cite box changes color not perfectly

show cite: it  => {
    show regex("\[(\d+)\]"): set text(main-color)
    it
}

should be

show cite: it  => {
    show regex("[\w\W]"): set text(main-color)
    it
}

2 header display may have some problems

..counterInt.slice(1,3)) should be ..counterInt.slice(0,2))
counterInt.len()> 2 should be counterInt.len()> 1

**Comment by flavio20002** [comment]
Thanks, I've merged those fix and I'm goint to update the package in the repository.

**Comment by flavio20002** [comment]
https://github.com/typst/packages/pull/1471
